### ISSUE TITLE
What is the meaning of 'program running on top of gem5' ？

### ISSUE THREAD

**Issue by AaAaYou** [farzadfch/gem5-cache-partitioning#1]
I am so grateful to this repos, but i have a question about the readme.md----"the function m5_enablewaypart must be called from the program running on top of gem5 with a non-zero integer passed to it as the argument. "

Which file is the top of gem5?

Look forward to your favourable reply.

**Comment by farzad64** [comment]
Sorry, the description is a bit misleading. `m5_enablewaypart` is **not** called from gem5 "top". You must write a C program which calls `m5_enablewaypart`. Then, invoke gem5 and pass the program binary so that the program runs in the simulated machine.

**Comment by AaAaYou** [comment]
Very well, thank you!
